### PR TITLE
This should pretty print object JSON.

### PR DESCRIPTION
**Pull request by JamesJeffryes**
Will make reviewing objects from the narrative much easier

### CODE REVIEW

**Comment by JamesJeffryes** [comment]
@kkellerlbl I haven't been able able to test this but it is pretty simple. Anyway to deploy on only CI to check it out?

**Comment by MrCreosote** [comment]
@JamesJeffryes This needs to be reverted. This would load all the object data from a file into memory which based on our experiments could take up to 20GB of memory.

**Comment by JamesJeffryes** [comment]
I'm confused, aren't WS objects limited to 1 GB? What other data would this pull into memory?

**Comment by MrCreosote** [comment]
1GB *when serialized*. When unpacked into maps, lists, references, and all that good stuff, memory use goes way up.

And even 1GB is too much - not sure how many threads this is configured with but if, say, 50 people are hitting the server at once...

**Pull request merged**
